[build]
  command = "npm --prefix my run build"
  publish = "my/dist"

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/admin-tasks"
  to = "/admin-tasks.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
